// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/pagination.proto

/*
Package pagination is a generated protocol buffer package.

It is generated from these files:
	protos/pagination.proto

It has these top-level messages:
	PaginationStatus
*/
package pagination

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaginationStatus struct {
	ParamsChecksum string `protobuf:"bytes,1,opt,name=params_checksum,json=paramsChecksum" json:"params_checksum,omitempty"`
	Cursor         string `protobuf:"bytes,2,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *PaginationStatus) Reset()                    { *m = PaginationStatus{} }
func (m *PaginationStatus) String() string            { return proto.CompactTextString(m) }
func (*PaginationStatus) ProtoMessage()               {}
func (*PaginationStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PaginationStatus) GetParamsChecksum() string {
	if m != nil {
		return m.ParamsChecksum
	}
	return ""
}

func (m *PaginationStatus) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

func init() {
	proto.RegisterType((*PaginationStatus)(nil), "pagination.PaginationStatus")
}

func init() { proto.RegisterFile("protos/pagination.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x48, 0x4c, 0xcf, 0xcc, 0x4b, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x03, 0x8b,
	0x08, 0x71, 0x21, 0x44, 0x94, 0x82, 0xb9, 0x04, 0x02, 0xe0, 0xbc, 0xe0, 0x92, 0xc4, 0x92, 0xd2,
	0x62, 0x21, 0x75, 0x2e, 0xfe, 0x82, 0xc4, 0xa2, 0xc4, 0xdc, 0xe2, 0xf8, 0xe4, 0x8c, 0xd4, 0xe4,
	0xec, 0xe2, 0xd2, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x3e, 0x88, 0xb0, 0x33, 0x54,
	0x54, 0x48, 0x8c, 0x8b, 0x2d, 0xb9, 0xb4, 0xa8, 0x38, 0xbf, 0x48, 0x82, 0x09, 0x2c, 0x0f, 0xe5,
	0x25, 0xb1, 0x81, 0xed, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x28, 0xdd, 0xee, 0x82,
	0x00, 0x00, 0x00,
}
